### ISSUE TITLE
el map no esta del todo bien implementado:

### ISSUE THREAD

**Issue by jupegarnica** [oscarval/Kata_redux#1]
https://github.com/oscarval/Kata_redux/blob/41b1aa425b696ad5039c267032d2c2fed62c9c2e/src/services/redux/reducer.js#L22-L30

cambiar todos por todo:
```
todos: state.todos.map((todo) => 
       todo.id === action.payload 
         ? { ...todo,  completed: !todos.completed } 
         : todo 
     ), 
```

**Comment by oscarval** [comment]
Gracias por el feedback. Solucionado!
