### ISSUE TITLE
Se está mutando el state.todo con el metodo splice

### ISSUE THREAD

**Issue by jupegarnica** [oscarval/Kata_redux#2]
https://github.com/oscarval/Kata_redux/blob/41b1aa425b696ad5039c267032d2c2fed62c9c2e/src/services/redux/reducer.js#L31-L37

Se está mutando el state.todo con el metodo splice y es posble que no encuetre bien todoDelete , yo lo implementaria asi:

```
case "DELETE_TODO": 
   const newTodos = state.todos.filter((todo) => todo.id !== action.payload); 
 
   return { 
     ...state, 
     todos: newTodos
   }; 
```

**Comment by oscarval** [comment]
Done! Gracias
